"use client";

import { FormEvent, useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Job={job_id:string;status:string;source_url:string;progress:number;message:string}; type Schedule={id:number;job_id:string;platform:string;scheduled_at:string;status:string}; type Published={id:number;platform:string;external_id:string|null;published_at:string|null;metrics:Record<string,unknown>}; type Summary={total_jobs:number;by_status:Record<string,number>}; type Analytics={published_total:number;by_platform:Record<string,number>}; type Account={id:number;platform:string;account_name:string;enabled:boolean}; type Trend={id:number;title:string;source_url:string;score:number;source:string;duration:number|null;discovered_at:string};

export default function Home(){
 const [jobs,setJobs]=useState<Job[]>([]),[summary,setSummary]=useState<Summary>({total_jobs:0,by_status:{}}),[schedules,setSchedules]=useState<Schedule[]>([]),[published,setPublished]=useState<Published[]>([]),[analytics,setAnalytics]=useState<Analytics>({published_total:0,by_platform:{}}),[accounts,setAccounts]=useState<Account[]>([]),[trends,setTrends]=useState<Trend[]>([]);
 const [url,setUrl]=useState(""),[loading,setLoading]=useState(false),[trendLoading,setTrendLoading]=useState(false),[error,setError]=useState("");
 async function refresh(){const [j,s,sc,p,a,ac,t]=await Promise.all([fetch(`${API}/api/v1/jobs`,{cache:"no-store"}),fetch(`${API}/api/v1/dashboard/summary`,{cache:"no-store"}),fetch(`${API}/api/v1/schedule`,{cache:"no-store"}),fetch(`${API}/api/v1/analytics/published?limit=20`,{cache:"no-store"}),fetch(`${API}/api/v1/analytics/summary`,{cache:"no-store"}),fetch(`${API}/api/v1/accounts`,{cache:"no-store"}),fetch(`${API}/api/v1/trends/stored?limit=12`,{cache:"no-store"})]);if([j,s,sc,p,a,ac,t].some(r=>!r.ok))throw new Error("API unavailable");setJobs(await j.json());setSummary(await s.json());setSchedules(await sc.json());setPublished(await p.json());setAnalytics(await a.json());setAccounts(await ac.json());setTrends(await t.json())}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(timer)},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!url.trim())return;setLoading(true);setError("");try{const r=await fetch(`${API}/api/v1/jobs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source_url:url.trim(),target_language:"vi",auto_publish:false})});if(!r.ok)throw new Error(await r.text());setUrl("");await refresh()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setLoading(false)}}
 async function cancel(id:number){try{const r=await fetch(`${API}/api/v1/schedule/${id}/cancel`,{method:"POST"});if(!r.ok)throw new Error(await r.text());await refresh()}catch(e){setError(e instanceof Error?e.message:"Cancel failed")}}
 async function discover(){setTrendLoading(true);try{const r=await fetch(`${API}/api/v1/trends?limit=20`,{cache:"no-store"});if(!r.ok)throw new Error(await r.text());setTrends((await r.json()).slice(0,12))}catch(e){setError(e instanceof Error?e.message:"Trend discovery failed")}finally{setTrendLoading(false)}}
 async function disable(id:number){try{const r=await fetch(`${API}/api/v1/accounts/${id}/disable`,{method:"POST"});if(!r.ok)throw new Error(await r.text());await refresh()}catch(e){setError(e instanceof Error?e.message:"Account update failed")}}
 const statuses=["DOWNLOADING","TRANSCRIBING","TRANSLATING"];
 return <main><header className="hero"><div><div className="eyebrow">AUTOMATION CONTROL CENTER</div><h1>ScanVideo</h1><p className="muted">Local-first AI video localization and publishing</p></div><div className="hero-status"><span className="dot"/>System online</div></header>{error&&<div className="alert">{error}</div>}
 <section className="card command"><strong>New localization job</strong><span className="muted"> · Videos under 10 seconds are rejected before download.</span><form className="form" onSubmit={submit}><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste an authorized source video URL…"/><button className="button" disabled={loading}>{loading?"Queueing…":"Create job"}</button></form></section>
 <section className="grid"><div className="card stat"><div className="muted">Total jobs</div><h2>{summary.total_jobs}</h2></div>{statuses.map(s=><div className="card stat" key={s}><div className="muted">{s}</div><h2>{summary.by_status[s]??0}</h2></div>)}<div className="card stat"><div className="muted">Published</div><h2>{analytics.published_total}</h2></div></section>
 <section className="panel"><div className="section-head"><div><div className="eyebrow">DISCOVERY</div><h2>Trend Discovery</h2><p className="muted">Public/authorized feeds ranked by the configured trend provider.</p></div><button className="button" onClick={discover} disabled={trendLoading}>{trendLoading?"Discovering…":"Discover trends"}</button></div><div className="trend-grid">{trends.length?trends.map(t=><article className="trend" key={t.id}><div className="trend-score">{t.score.toFixed(1)}</div><div><strong>{t.title}</strong><div className="muted">{t.source} · {t.duration?`${Math.round(t.duration)}s`:"duration unknown"}</div><a href={t.source_url} target="_blank" rel="noreferrer">Open source ↗</a></div></article>):<div className="empty">No stored trends yet. Run discovery to populate this panel.</div>}</div></section>
 <section className="panel"><div className="section-head"><div><div className="eyebrow">PUBLISHING</div><h2>Connected Accounts</h2><p className="muted">Credentials remain outside the repository.</p></div><div className="oauth-actions"><a className="button secondary" href={`${API}/api/v1/oauth/youtube/start`}>Connect YouTube</a><a className="button secondary" href={`${API}/api/v1/oauth/tiktok/start`}>Connect TikTok</a></div></div><div className="account-grid">{accounts.length?accounts.map(a=><div className="account" key={a.id}><div className={`platform ${a.platform}`}>{a.platform.toUpperCase()}</div><div><strong>{a.account_name}</strong><div className="muted">{a.enabled?"Enabled":"Disabled"}</div></div>{a.enabled&&<button className="button danger" onClick={()=>disable(a.id)}>Disable</button>}</div>):<div className="empty">No publishing accounts connected yet.</div>}</div></section>
 <section className="panel"><h2>Jobs</h2><table className="table"><thead><tr><th>Job</th><th>Status</th><th>Progress</th><th>Message</th></tr></thead><tbody>{jobs.map(j=><tr key={j.job_id}><td>{j.job_id.slice(0,12)}</td><td><span className="badge">{j.status}</span></td><td>{j.progress}%</td><td>{j.message}</td></tr>)}</tbody></table></section>
 <section className="panel"><h2>Schedule</h2><table className="table"><thead><tr><th>Platform</th><th>Job</th><th>When</th><th>Status</th><th/></tr></thead><tbody>{schedules.map(s=><tr key={s.id}><td>{s.platform}</td><td>{s.job_id.slice(0,12)}</td><td>{new Date(s.scheduled_at).toLocaleString()}</td><td><span className="badge">{s.status}</span></td><td>{s.status==="SCHEDULED"&&<button className="button danger" onClick={()=>cancel(s.id)}>Cancel</button>}</td></tr>)}</tbody></table></section>
 <section className="panel"><h2>Published & Analytics</h2><table className="table"><thead><tr><th>Platform</th><th>External ID</th><th>Published</th><th>Views</th><th>Likes</th><th>Comments</th></tr></thead><tbody>{published.map(p=>{const m=p.metrics||{};return <tr key={p.id}><td>{p.platform}</td><td>{p.external_id||"—"}</td><td>{p.published_at?new Date(p.published_at).toLocaleString():"—"}</td><td>{String(m.views??"—")}</td><td>{String(m.likes??"—")}</td><td>{String(m.comments??"—")}</td></tr>})}</tbody></table></section>
 </main>;
}
